[project]
name = "hina"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kivy>=2.3.1",
    "pip>=25.1.1",
]

[dependency-groups]
dev = [
    "buildozer>=1.5.0",
    "ruff>=0.11.8",
]
